require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'applozicTest' do
  config = use_native_modules!
  use_frameworks!
  pod 'Applozic', "~> 7.4.0", :modular_headers => true
  
  use_react_native!(:path => config["reactNativePath"])

  target 'applozicTestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'applozicTest-tvOS' do
  # Pods for applozicTest-tvOS

  target 'applozicTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

